[tool.poetry]
name = "mltools"
version = "0.1.0"
description = ""
authors = ["Yuki Wada <yuki.w.228285@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.19.5"
pandas = "^1.2.0"
tqdm = "^4.56.0"
mecab-python-windows = [
    { version = "0.996.3", platform = 'win32' }
]
mecab-python3 = [
    { version = "0.996.3", platform = 'linux' }
]
dill = "^0.3.3"
matplotlib = "^3.3.3"
torch = {url = "https://download.pytorch.org/whl/cu110/torch-1.7.1%2Bcu110-cp39-cp39-win_amd64.whl"}
autopep8 = "^1.5.5"
gensim = "^3.8.3"

[tool.poetry.dev-dependencies]
pylint = "^2.6.0"
autopep8 = "^1.5.5"
flake8 = "^3.8.4"
mypy = "^0.812"

[tool.poetry.extras]
cython = ["Cython"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
